language: android
dist : trusty
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-29.0.1

    # The SDK version used to compile your project
    - android-29

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-29
    - sys-img-armeabi-v7a-android-17

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "build-tools;28.0.3"
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.1"

before_script:
  - touch local.properties

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

script:
  - ./gradlew clean build
